Pharmacovigilance updates
medic/cht-accelerator pull request #21
Opened 2023-09-29 02:17 UTC by Itskiprotich

UHC mode dropped & unit tests updated

2023-10-05 07:50 UTC, esthermmoturi commented
<img width="876" alt="image" src="https://github.com/medic/cht-accelerator/assets/112471942/899e262d-1256-4710-b5e3-3f37a3bea557">
Primary contact is saved under 'People' while added members are saved under 'Household members'.Could you place them under the same card?

2023-10-05 08:08 UTC, esthermmoturi commented
- [ ] In the `Assessment Form`, the question `**Did you notice anything strange with your medicine?**` is still asked after the user answers `No` to the question `**Are you currently taking any medication?**`
- [ ] Consider using vaccination for over 5s and immunization for u5 in this question `**Have you recently received any vaccination/immunization?**`
- [ ] Indicate relevance for all questions eg when answered No or Yes, which subsequent questions should/shouldn't appear.
- [ ] Add monthly targets (unless all time targets fit your needs)
- [ ] While logged in as a CHA/Supervisor, should I be able to create a supervisor region? Or should I just be able to create an Area?

2023-10-05 08:08 UTC, esthermmoturi requested changes
@Itskiprotich Kindly review the comments

2023-10-09 07:12 UTC, Itskiprotich commented
@esthermmoturi here is my response to the above:

- [x] In the Assessment Form, the question **Did you notice anything strange with your medicine?** is still asked after the user answers No to the question **Are you currently taking any medication?**  -> The first question is under the adverse reactions while the other falls under the poor quality medicine. I've updated the form to show the sections clearly.
- [x]  Consider using vaccination for over 5s and immunization for u5 in this question **Have you recently received any vaccination/immunization?**  -> Let me have an internal discussion with the team
- [x]  Indicate relevance for all questions eg when answered No or Yes, which subsequent questions should/shouldn't appear. -> This is in place, check the assessment form the *Severe Adverse Reactions* section, 
- [x]  Add monthly targets (unless all time targets fit your needs). This has been implemented, thank you for pointing out.
- [x]  While logged in as a CHA/Supervisor, should I be able to create a supervisor region? Or should I just be able to create an Area? -> No, the supervisor region is only created at the facility level.

2023-10-13 05:44 UTC, esthermmoturi commented on IntelliSOFT/Example CHT application/cht_pvers/translations/messages-en.properties
> +poor.quality.medicine.reported.title=Poor Quality Medicine Reported Reported
```suggestion
poor.quality.medicine.reported.title=Poor Quality Medicine Reported
```

2024-02-22 07:09 UTC, closed without merging