Targets Aggregates
medic/cht-accelerator pull request #28
Opened 2024-01-30 06:14 UTC by Itskiprotich

2024-02-19 06:59 UTC, esthermmoturi requested changes
@Itskiprotich kindly address suggestions provided.

2024-02-19 06:59 UTC, esthermmoturi commented on IntelliSOFT/Example CHT application/cht_pvers/targets.js
> +
```suggestion
 // Target for number of households registered by a specific CHP
```

2024-02-19 06:59 UTC, esthermmoturi commented on IntelliSOFT/Example CHT application/cht_pvers/targets.js
> +    type: 'percent',
```suggestion
    type: 'count',
```

2024-02-19 06:59 UTC, esthermmoturi commented on IntelliSOFT/Example CHT application/cht_pvers/targets.js
> +    type: 'percent',
Since the number of households registered is not against something/another metric, it's good to maintain it as `count.` `Percent` would be used in a case like number of households with adverse drug reactions vs total number of households. What do you think?

2024-02-19 06:59 UTC, esthermmoturi commented on IntelliSOFT/Example CHT application/cht_pvers/targets.js
> +    goal: 75,
```suggestion
    goal: 15,
```

2024-02-19 06:59 UTC, esthermmoturi commented on IntelliSOFT/Example CHT application/cht_pvers/targets.js
> +    context: 'user.contact_type === "chw"',
```suggestion
    context: 'user.role === "chw"',
```

2024-02-19 06:59 UTC, esthermmoturi commented on IntelliSOFT/Example CHT application/cht_pvers/targets.js
> +    groupBy: contact => getHouseholdId(contact),
```suggestion
```

2024-02-19 06:59 UTC, esthermmoturi commented on IntelliSOFT/Example CHT application/cht_pvers/targets.js
> +    passesIfGroupCount: { gte: 2 }
```suggestion
```

2024-02-19 14:21 UTC, Itskiprotich commented
@esthermmoturi the suggestions are in order. Thanks

2024-02-22 07:11 UTC, esthermmoturi approved these changes

2024-02-22 07:16 UTC, esthermmoturi commented
Hey @Itskiprotich , kindly push all the recent changes to your test instance for me to do the final test.

2024-03-03 04:41 UTC, merged